### ISSUE TITLE
env_sky Skybox Tint Color doesn't work anymore

### ISSUE THREAD

**Issue by Ephememory** [Facepunch/sbox-issues#2090]
### Describe the bug

Try tint sky color, it doesn't tint.

### To Reproduce

1. Tint an env_sky of any kind, texture sky mat or color sky mat.
2. In game it has no effect, inspector shows the selected color and changing it in the inspector does nothing either.

### Expected behavior

Tint my skies to get free night time sky boxes.

**Comment by robotboy655** [comment]
Should be fixed.

**Comment by Ephememory** [comment]
> Should be fixed.

![image](https://user-images.githubusercontent.com/66768086/182391783-d706050d-ac3e-421a-bdc5-b72d73c6ced4.png)
![image](https://user-images.githubusercontent.com/66768086/182391810-c3680bda-64a3-4d9c-a8ca-23a647f09c64.png)
![image](https://user-images.githubusercontent.com/66768086/182391933-fbe58dec-41d6-4787-b06d-b05a8ae6a484.png)
Still present for me after game update and after restarting Steam. Am I missing a step or doing something wrong?
