### ISSUE TITLE
Error loading local addons with targets while starting packaged games

### ISSUE THREAD

**Issue by MuffinTastic** [Facepunch/sbox-issues#2449]
### Describe the bug

When starting a packaged game with a local addon enabled that targets it, e.g. packaged/cloud `facepunch.sandbox` and a local addon that specifically targets `facepunch.sandbox`, it fails to find the packaged game's assembly and the addon does not load.

### To Reproduce

1. Make sure you don't have an local version of `facepunch.sandbox` enabled that would interfere
2. Add this [sandbox_tool_poc](https://github.com/Facepunch/sbox-issues/files/9891249/sandbox_tool_poc.zip) addon project locally
3. Start `facepunch.sandbox`, downloaded from the backend
4. See the error as it tries to load the addon

### Expected behavior

The addon should load properly

### Media/Files

![sbox-dev_IIKkC837c8](https://user-images.githubusercontent.com/10884425/198718112-b35a99d2-bee5-48a8-91f1-3c5886cfc0b6.png)

**Comment by garrynewman** [comment]
This should be fixed next build

**Comment by MuffinTastic** [comment]
It is now differently broken
```
2022/10/29 08:55:36.131	menu	Set parameters Async local.repro_addon	
2022/10/29 08:55:40.646	Console	Loading map "wallsurf.moose_city"	
2022/10/29 08:55:40.798	server	Downloading local.repro_addon	
2022/10/29 08:55:40.798	server	Finding Package local.repro_addon	
2022/10/29 08:55:40.798	server	local.repro_addon found - but it has no usable manifest	
2022/10/29 08:55:42.157	Server	SV:  maxplayers set to 64	
2022/10/29 08:55:43.059	Generic	Activating local extension 'repro_addon'	
2022/10/29 08:55:43.102	tools	Not in whitelist: Unknown Assembly package.facepunch.sandbox (System.NotSupportedException)
   at Sandbox.AssemblyResolver.Resolve(String simpleName)
   at ILVerify.ILVerifyTypeSystemContext.ResolveAssembly(AssemblyName name, Boolean throwIfNotFound)
   at Internal.TypeSystem.Ecma.EcmaModule.ResolveAssemblyReference(AssemblyReferenceHandle handle)
   at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle)
   at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
   at Internal.TypeSystem.Ecma.EcmaModule.ResolveTypeReference(TypeReferenceHandle handle)
   at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle)
   at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
   at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle handle)
   at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType()
   at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags mask)
   at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags mask)
   at Internal.IL.ILImporter..ctor(MethodDesc method, MethodIL methodIL)
   at ILVerify.Verifier.VerifyMethod(EcmaModule module, MethodIL methodIL, MethodDefinitionHandle methodHandle)
   at ILVerify.Verifier.VerifyMethods(EcmaModule module, IEnumerable`1 methodHandles)+MoveNext()
   at ILVerify.Verifier.Verify(PEReader peReader)+MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at Sandbox.AccessILVerify.DoVerify(PEReader pe)
   at Sandbox.AccessControl.VerifyIL(Stream dllStream)
   at Sandbox.AccessControl.VerifyAssembly(Stream dll, TrustedBinaryStream& outStream, Boolean addToWhitelist)	
2022/10/29 08:55:43.102	tools	Not loading package.local.repro_addon because it failed access control.	
2022/10/29 08:55:43.102	server	ServerDll: Access Control [package.local.repro_addon]	
2022/10/29 08:55:43.102	server	ServerDll: Loading [package.local.repro_addon]	
2022/10/29 08:55:43.566	server	Adding network files from [Addon:local.repro_addon]	
2022/10/29 08:55:43.566	server	Adding Code Path: C:\users\muffin\saved games\s&box\addons\repro_addon\code	
2022/10/29 08:55:43.566	server	Adding Content Path: C:\users\muffin\saved games\s&box\addons\repro_addon	
2022/10/29 08:55:44.411	ResourceSystem	Error loading resource file "maps/moose_city/world_visibility.vvis_c" (Error: ERROR_FILEOPEN)	
2022/10/29 08:55:44.439	server	CreateEntityFromEngine: Unknown entity 'ambient_generic'	
2022/10/29 08:55:44.458	server	CreateEntityFromEngine: Unknown entity 'ambient_generic'	
2022/10/29 08:55:44.458	server	CreateEntityFromEngine: Unknown entity 'ambient_generic'	
2022/10/29 08:55:44.504	ResourceSystem	Error loading resource file "maps/prefabs/moose_city/skybox/world_visibility.vvis_c" (Error: ERROR_FILEOPEN)	
2022/10/29 08:55:46.614	Entity System	ExecuteQueuedCreation() took 327778us [ Spawned: 347, Activated 347, PostDataUpdate: 0, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]	
2022/10/29 08:55:46.658	server	"MuffinTastic" has joined the game
```

This is the target
![image](https://user-images.githubusercontent.com/10884425/198840834-dd780b2a-7bcf-4a09-a966-cb7ca5a5d2d4.png)

And here's the only code in the addon. To get it to error you need to directly reference the game's assembly like I do here with BalloonEntity
```cs
namespace Sandbox
{
    internal class Class1 : BalloonEntity
    {
    }
}
```

**Comment by garrynewman** [comment]
That should still work - it's just a tools error - which I'll fix in a different way.

**Comment by MuffinTastic** [comment]
Oh yeah, sure enough, it does work in-game. Should've paid more attention to which subsystem was complaining. I'll let you decide whether or not to close this issue

**Comment by Ephememory** [comment]
I think I'm still experiencing this.
![image](https://user-images.githubusercontent.com/66768086/209411645-f4df4362-0f9c-4c75-8fe2-d6d04db5cbc3.png)
![image](https://user-images.githubusercontent.com/66768086/209411649-901a29ad-c2a0-4790-9ffc-30c613ffce17.png)
```
04:50:28   engine/AssetSystem AssetSystem initialized in 1.61 seconds. [0.05 load, 0.12 scan, 1.42 dependencies, 0.02 save]
 04:51:05   engine/Engine Couldn't open addon file (E:\edev\sbox-projects\.addonstier2\duplicator\.addon\.addon) - addon content won't be filesystem mounted
 04:51:05   Compiler/null.duplicator Couldn't find package.facepunch.sandbox.dll
 04:52:17   engine/Console Loading map "aero.roblox_baseplate"
 04:52:17   Server Downloading null.duplicator#local
 04:52:17   Server Finding Package null.duplicator#local
 04:52:17   engine/Server SV:  maxplayers set to 1
 04:52:18   engine/Engine WARNING: unable to link say and say because both ConCommands are not marked FCVAR_LINKED_CONCOMMAND
 04:52:18   Server Adding network files from [[Addon:null.duplicator]](arg:0)
 04:52:18   Server Adding Code Path: E:\edev\sbox-projects\.addonstier2\duplicator\code
 04:52:18   Server Adding Content Path: E:\edev\sbox-projects\.addonstier2\duplicator
 04:52:19   engine/Engine WARNING: unable to link chat_add and chat_add because both ConCommands are not marked FCVAR_LINKED_CONCOMMAND
 04:52:20   engine/Engine CNavGenParams - Nav mesh requests project default generation parameters but actual parameters   used during construction differ from defaults. Please re-export the map.
 ```

When developing/testing an addon locally, it appears as if we don't have the target gamemode .dll referenced. So trying to use any types defined there throw compiler errors, obviously. 
![image](https://user-images.githubusercontent.com/66768086/209411836-a6f97b0b-a7f1-4c01-9830-b5e9db7e41e4.png)

Addon works normally when testing from the cloud in a live game session.
