### ISSUE TITLE
Game Crashes after sometime in the Face punch logo

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [Facepunch/sbox-issues#3579]
### Describe the bug

I'm not sure what happened, the day before the game was launching fine with no issues at all, but after an update now the game crashes after some time in the face punch logo, i have no idea since launching the game in editor model opens fine.

I've tried to verfy the game integrity but that didn't do anything, i tried to re-install the game and the problem still exists.

EDIT: My steam ID is 76561198116511493

### To Reproduce

1. Open the game on steam.
2. Choose "Play s&box"
3. Wait sometime in the face punch logo
4. The game crashes

### Expected behavior

The game should open fine, the fact that the game boots up fine in editor mode really confuses me

### Media/Files

```
2023/07/08 17:58:40.4847	engine/Engine	SteamAPI_Init succeeded.  SteamID is [U:1:156245765] (76561198116511493), AppID is 590830	
2023/07/08 17:58:40.5462	engine/Steam	CSteam3Client::Activate succeeded.  SteamID is [U:1:156245765] (76561198116511493), AppID is 590830	
2023/07/08 17:58:43.1552	Generic	Trying to restore menu cookies from a backup...	
2023/07/08 17:58:43.1552	Generic	Failed to load menu cookies from disk!	
2023/07/08 17:58:43.2473	Generic	Trying to restore gamemmenu cookies from a backup...	
2023/07/08 17:58:43.2473	Generic	Failed to load gamemmenu cookies from disk!	
2023/07/08 17:58:44.9112	engine/RenderSystem	Saved video settings config to 'cfg\video.txt'	
2023/07/08 17:58:46.4772	engine/RenderSystem	Saved video settings config to 'cfg\video.txt'	
```

### Additional context

Here's my PC Specs:

- OS: Windows 10 Pro x64
- CPU: Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz   2.71 GHz
- Ram: 16.0 GB
- GPU: Intel(R) HD Graphics 630

**Comment by FriskTheFallenHuman** [comment]
Bump: The Update of today doesn't fix this issue yet

**Comment by FoggyFella** [comment]
I'm having the same issue

**Comment by FriskTheFallenHuman** [comment]
Bump 2: The two last updates doesn't fix this crash, i can confidently say it is not a driver issue since i can boot just fine in editor mode

**Comment by aylaylay** [comment]
There's nothing in sentry with your steam id

**Comment by FriskTheFallenHuman** [comment]
> There's nothing in sentry with your steam id

@aylaylay The problem its the game prematurely quicks before even generating a sentry report.

https://github.com/sboxgame/issues/assets/12750944/5222482d-d85c-4cee-a52f-f4bce10ab17f

After it crash there's, nothing logged in the log:

```
2023/07/09 16:25:17.2411	engine/Engine	SteamAPI_Init succeeded.  SteamID is [U:1:156245765] (76561198116511493), AppID is 590830	
2023/07/09 16:25:17.3188	engine/Steam	CSteam3Client::Activate succeeded.  SteamID is [U:1:156245765] (76561198116511493), AppID is 590830	
```

It gets weird when it boots fine into editor mode:

https://github.com/sboxgame/issues/assets/12750944/2315cc12-1517-495a-8b0e-ad5e129ba746

**Comment by aylaylay** [comment]
There's not much I can do if it's not showing up on sentry or without any other info

**Comment by handsomematt** [comment]
So iirc OP's issue here was Intel Graphic Drivers crashing on sbox.exe, renaming the exe magically fixed it.

Are other people still having this issue? If so can you post your specs, log files and if it's just sbox.exe that's broken or sbox-dev.exe also?

**Comment by SteveExodus** [comment]
I can Tell U what fixed my black Screen Problem..
https://github.com/sboxgame/issues/issues/3623#issue-1806025029

M$ bugged win10 some month ago With an Update. A Problem With SSL/ TLS Connections.

I Had to disable TLS 1.3 in the registry (shouldnt be even active in win10, dont ask me why It was active.)

The article can maybe Help U all (U can Change IT to english)

https://borncity.com/win/2022/10/22/fix-des-ssl-tls-verbindungsproblems-stand-der-sonderupdates-und-betroffene-anwendungen-21-10-2022/

**Comment by Reoxur** [comment]
I'm having the same issue, launch, hangs on the Logo, crashes 

Log only says 

"2023/07/28 16:06:42.4049	engine/Engine	SteamAPI_Init succeeded.  SteamID is [U:1:33016803] (76561197993282531), AppID is 590830	
2023/07/28 16:06:42.4699	engine/Steam	CSteam3Client::Activate succeeded.  SteamID is [U:1:33016803] (76561197993282531), AppID is 590830"


OS:  Microsoft Windows 10 Home (x64) Build 19045.3208
GPU: NVIDIA GeForce RTX 3060 Ti LHR  (Last time I opened S&box was with a GTX 1050 TI)
CPU: AMD Ryzen 5 1600
RAM: 16 GB

**Comment by Reoxur** [comment]
Ok weird I fixed it

I'm unsure what I did exactly.

Basically, I installed .net 7.0.7 and 7.0.2 
It was still crashing
Went to Taskmanager>Services 
Started stopping things such as "Network Connection Broker" and "Connected Devices Platform User Service" or anything related to those names.

Suddenly it works, S&box launched and worked fine.

**Comment by wuangg** [comment]
I'm having the same issue as well, hangs in logo and outright crash itself, doesn't even make it to the menu.

OS: Microsoft Windows 10 21H2 (x64)
CPU: Intel i7-9750H
GPU: Intel UHD Graphics 630 + NVIDIA GeForce GTX 1650
Ram: 16GB
GPU Driver Version: 31.0.101.2125 (Intel UHD Graphics 630), 536.67 (NVIDIA GeForce GTX 1650)

sbox log:
```
2023/07/31 00:58:33.6634	engine/Engine	SteamAPI_Init succeeded.  SteamID is [U:1:206388823] (76561198166654551), AppID is 590830	
2023/07/31 00:58:33.9575	engine/Steam	CSteam3Client::Activate succeeded.  SteamID is [U:1:206388823] (76561198166654551), AppID is 590830	
2023/07/31 00:58:38.0421	engine/RenderSystem	Couldn't find driver version for device 'NVIDIA GeForce GTX 1650'	
2023/07/31 00:58:40.0470	engine/Engine	CAppSystemDict:Unable to load module video (Dependency of application), error 127	
2023/07/31 00:58:43.3929	Generic	Create Compiler `base`	
2023/07/31 00:58:43.5314	Generic	Create Compiler `local.menu`	
2023/07/31 00:58:44.3489	Generic	Trying to restore client cookies from a backup...	
2023/07/31 00:58:44.3507	Generic	Failed to load client cookies from disk!	
2023/07/31 00:58:44.5083	GameMenu	Couldn't find Input Action called "voice"	
```

sbox-dev log:
```
2023/07/31 01:04:58.6670	engine/Engine	SteamAPI_Init succeeded.  SteamID is [U:1:206388823] (76561198166654551), AppID is 590830	
2023/07/31 01:04:58.7795	engine/Steam	CSteam3Client::Activate succeeded.  SteamID is [U:1:206388823] (76561198166654551), AppID is 590830	
2023/07/31 01:05:01.9201	engine/RenderSystem	Couldn't find driver version for device 'NVIDIA GeForce GTX 1650'	
2023/07/31 01:05:16.5165	engine/HangWatchdog	Hang detected.	
2023/07/31 01:05:16.9323	engine/AssetSystem	AssetSystem initialized in 6.25 seconds. [0.11 load, 0.65 scan, 5.44 dependencies, 0.03 save]	
2023/07/31 01:05:16.9735	engine/Engine	CAppSystemDict:Unable to load module video (Dependency of application), error 127	
2023/07/31 01:05:25.3878	engine/HangWatchdog	Hang detected.	
2023/07/31 01:05:32.7235	engine/HangWatchdog	Hang detected.	
2023/07/31 01:05:34.5617	Generic	Create Compiler `base`	
2023/07/31 01:05:34.6803	Generic	Create Compiler `local.menu`	
2023/07/31 01:05:34.7058	Generic	Create Compiler `toolbase`	
2023/07/31 01:05:34.7276	Generic	Create Compiler `local.entityprefabed`	
2023/07/31 01:05:34.7464	Generic	Create Compiler `local.shadergraph`	
2023/07/31 01:05:39.9136	engine/HangWatchdog	Hang detected.	
2023/07/31 01:05:45.1702	engine/HangWatchdog	Hang detected.	
2023/07/31 01:05:50.3691	engine/HangWatchdog	Hang detected.	
2023/07/31 01:06:08.7839	engine/HangWatchdog	Hang detected.	
2023/07/31 01:06:11.9408	Generic	Trying to restore client cookies from a backup...	
2023/07/31 01:06:11.9496	Generic	Failed to load client cookies from disk!	
2023/07/31 01:06:12.1263	GameMenu	Couldn't find Input Action called "voice"	
```

Event Viewer:
```
Application: sbox.exe
CoreCLR Version: 7.0.723.27404
.NET Version: 7.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at NativeEngine.EngineGlobal.SourceEngineInit(CMaterialSystem2AppSystemDict)
   at Sandbox.SourceEngineApp.Initialize()
   at Sandbox.Program.LaunchGame()
   at Sandbox.Program.Main()
```
```
Faulting application name: sbox.exe, version: 1.0.1.0, time stamp: 0x6492041a
Faulting module name: coreclr.dll, version: 7.0.723.27404, time stamp: 0x646e214e
Exception code: 0xc0000005
Fault offset: 0x00000000001c9f06
Faulting process id: 0x3064
Faulting application start time: 0x01d9c30c26f19c21
Faulting application path: D:\SteamLibrary\steamapps\common\sbox\sbox.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.7\coreclr.dll
Report Id: 287a0e85-0d0e-406b-a1f5-531cb5efddc5
Faulting package full name: 
Faulting package-relative application ID: 
```

Already tried completely re-installing the game, re-installing graphics drivers

My Steam64 ID: 76561198166654551

**Comment by wuangg** [comment]
Bump, the issue hasn't been fixed yet

**Comment by wuangg** [comment]
The bug has been resolved (for me) in some of today's game updates

**Comment by bladistay** [comment]
Bump

**Comment by yuberee** [comment]
> Bump

If you're gonna bump at least post your steamid.

**Comment by yuberee** [comment]
Someone on the Facepunch forums managed to fix a similar (Or maybe the same?) issue.
If anyone encountering this could try these steps and let us know if they work it would massively help:

1. Open Device Manager
2. Find your graphics card under "Display Adapter"
3. Right click -> Disable -> Right click -> Enable
4. Press CTRL+SHIFT+WIN+B to reload Graphics Driver
5. Verify Game Files Integrity on Steam
6. Restart your Computer
7. Try launching the game

I'm assuming some of these steps are redundant, but it's a good for troubleshooting.

**Comment by Reoxur** [comment]
I tried the steps but still crashes after it hangs on launch for like 2 min every time 

```
Faulting application name: sbox.exe, version: 1.0.1.0, time stamp: 0x64e841c5
Faulting module name: coreclr.dll, version: 7.0.1023.36312, time stamp: 0x64b06d6c
Exception code: 0xc0000005
Fault offset: 0x00000000001c98a6
Faulting process id: 0x239c
Faulting application start time: 0x01d9f1ee4528839b
Faulting application path: G:\SteamLibrary\steamapps\common\sbox\sbox.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Report Id: 97013857-5820-4338-8baa-7ab0b2ec4150
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Reoxur** [comment]
Can confirm this has been fixed for me, for a long while now
