### ISSUE TITLE
Transitions don't work without setting default values

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#3864]
### Describe the bug

This behavior broke somewhere between the 4th and 16th of august.
For opacity you can fix it by giving the initial property a value (example below), for other properties like margin I haven't found a workaround.

https://github.com/sboxgame/issues/assets/4988198/2698a73c-f08b-49fb-983e-91188ec4d645

### Doesn't work:
```css
& > .status {
    transition: opacity 1s ease-out;

    &.hide {
        opacity: 0;
    }
}
```

### Works:
```css
& > .status {
    transition: opacity 1s ease-out;
    opacity: 1;

    &.hide {
        opacity: 0;
    }
}
```

**Comment by DevulTj** [comment]
@xezno merged some work that should resolve the issues that you are having with UI - do let us know if you continue to have any problems

**Comment by xezno** [comment]
Will have a look

**Comment by timmybo5** [comment]
Did your fixes affect keyframes?

My opacity keyframes do not seem to work anymore:
```css

.label {
    color: white;
    font-size: 16px;
    animation-name: opacityFlicker;
    animation-duration: 1s;
    animation-timing-function: linear;
}

@keyframes opacityFlicker {
    0% {
        opacity: 0.1;
    }

    50% {
        opacity: 1;
    }

    100% {
        opacity: 0.1;
    }
}
```

The text now remains at this opacity:
![image](https://github.com/sboxgame/issues/assets/4988198/3bc7bc35-440e-4616-b039-22e750dd73b5)

**Comment by xezno** [comment]
You need to specify an `animation-iteration-count`, the default value for this was changed to 1 instead of infinite (to match spec)

**Comment by timmybo5** [comment]
Just letting you know that margin transitions are still not working

**Comment by xezno** [comment]
> Just letting you know that margin transitions are still not working

They seem to be working fine

https://github.com/sboxgame/issues/assets/12881812/a82f28e0-f2fc-436b-8490-d501771f7670

```html
<style>
.box {
	background-color: red;
	width: 50px;
	height: 50px;

	transition: all 150ms ease;

	&:hover {
		margin-left: 10px;
	}
}
</style>

<root>	
	<panel class="box"></panel>
</root>
```
