### ISSUE TITLE
DebugOverlay renders wrong in VR

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#604]

**Comment by samzanemesis** [comment]
Duplicate of https://github.com/Facepunch/sbox-issues/issues/595 ?

**Comment by ShadowBrian** [comment]
This needs re-verification in the Steam build of the game.
If you want a sort of quick test you can boot up my Climbing gamemode with controllers on and aim at a surface, it should show a green circle on the hit point but instead it's warped like the original issue.

Might have been fixed internally though, but the actual Steam build doesn't seem to have it fixed...

**Comment by samzanemesis** [comment]
Still happens on Steam build with VR instancing enabled, will push a fix in a moment

**Comment by garrynewman** [comment]
Looks like DebugOverlay.Text still renders funny

**Comment by garrynewman** [comment]
Also, the Frustum culling seems to be a bit weird in vr on regular line drawing too
