### ISSUE TITLE
Light rendering messed up in orthographic view

### ISSUE THREAD

**Issue by stellawisps** [Facepunch/sbox-issues#6488]
### Describe the bug

Light rendering depends on camera position in orthographic, and lights will disappear/appear tiled depending on camera position.

### To Reproduce

1. Set camera to orthographic
2. Move it in and out of light radius

### Expected behavior

Lights should render normally independent of camera position in orthographic view.

### Media/Files

https://github.com/user-attachments/assets/f3602c78-faf4-44cf-b81c-f21aeaac3313

[orthocamrepro.zip](https://github.com/user-attachments/files/17091459/orthocamrepro.zip)
repro project

**Comment by handsomematt** [comment]
We mess a lot of things up in ortho view, need to look at it all

**Comment by MrBrax** [comment]
reflections don't work either in ortho, separate issue?

**Comment by samzanemesis** [comment]
Fixed internally just waiting code review

> reflections don't work either in ortho, separate issue?

I've added a test scene to track it, I'll revist it hopefully still this week

**Comment by samzanemesis** [comment]
Please try again

**Comment by stellawisps** [comment]
Lights now work as expected in ortho, however in my repro there is some weirdness on the edges still but a massive improvement nonetheless https://github.com/user-attachments/assets/6e8f2620-8775-4f4d-82c4-a0a171c50ddc

**Comment by CarsonKompon** [comment]
I'm still experiencing this issue in my 2D project. Here's a video for reference:

https://github.com/user-attachments/assets/6e7943bb-4270-4497-a10c-53449b83f17e

Sun light from the day/night cycle works just fine but any spot/point lights will not appear when in Orthographic mode

**Comment by sampavlovic** [comment]
should be gucci now, please re-review

**Comment by CarsonKompon** [comment]
Still doesn't seem like it's working for me 😳

https://github.com/user-attachments/assets/f32be1fd-cb51-46f4-be74-08ad38eec9d8

**Comment by CarsonKompon** [comment]
Now that everything's been merged with the June update it seems to be working just fine 👍 

https://github.com/user-attachments/assets/6e41708c-27c0-4b03-b987-877f39e51705

**Comment by stellawisps** [comment]
Looks good to me 👍
